
#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 1

#define LV_FONT_ANTIALIAS 0
#define LV_USE_FONT_SUBPX 0



#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_20 1

#define LV_FONT_MONTSERRAT_28 1
